name: CI for Terraform

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Check failure
        if: failure()
        run: exit 1

      - name: Print on Success
        if: ${{ success() }}
        run: echo "The Terraform workflow run was successful."
